// Toast
export const SHOW_TOAST = "SHOW_TOAST";
export const HIDE_TOAST = "HIDE_TOAST";

// User
export const ERROR_RECEIVE_USER = "ERROR_RECEIVE_USER";
export const REQUEST_USER = "REQUEST_USER";
export const RECEIVE_USER = "RECEIVE_USER";

export const ERROR_SIGN_IN = "ERROR_SIGN_IN";
export const REQUEST_SIGN_IN = "REQUEST_SIGN_IN";
export const SUCCESS_SIGN_IN = "SUCCESS_SIGN_IN";

export const ERROR_SIGN_UP = "ERROR_SIGN_UP";
export const REQUEST_SIGN_UP = "REQUEST_SIGN_UP";
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP";

export const REQUEST_SIGN_OUT = "REQUEST_SIGN_OUT";

// MoviesList
export const REQUEST_MOVIES = "REQUEST_MOVIES";
export const RECEIVE_MOVIES = "RECEIVE_MOVIES";
export const ERROR_MOVIES = "ERROR_MOVIES";

// DeleteMovie
export const REQUEST_DELETE_MOVIE = "REQUEST_DELETE_MOVIE";
export const SUCCESS_DELETE_MOVIE = "SUCCESS_DELETE_MOVIE";
export const ERROR_DELETE_MOVIE = "ERROR_DELETE_MOVIE";

// MovieDetails
export const REQUEST_MOVIE_DETAILS = "REQUEST_MOVIE_DETAILS";
export const RECEIVE_MOVIE_DETAILS = "RECEIVE_MOVIE_DETAILS";
export const ERROR_MOVIE_DETAILS = "ERROR_MOVIE_DETAILS";
export const CLEAR_MOVIE_DETAILS = "CLEAR_MOVIE_DETAILS";

// NewMovie
export const REQUEST_CREATE_MOVIE = "REQUEST_CREATE_MOVIE";
export const SUCCESS_CREATE_MOVIE = "SUCCESS_CREATE_MOVIE";
export const ERROR_CREATE_MOVIE = "ERROR_CREATE_MOVIE";

// EditMovie
export const REQUEST_UPDATE_MOVIE = "REQUEST_UPDATE_MOVIE";
export const SUCCESS_UPDATE_MOVIE = "SUCCESS_UPDATE_MOVIE";
export const ERROR_UPDATE_MOVIE = "ERROR_UPDATE_MOVIE";

// Directors
export const REQUEST_DIRECTORS = "REQUEST_DIRECTORS";
export const RECEIVE_DIRECTORS = "RECEIVE_DIRECTORS";
export const ERROR_DIRECTORS = "ERROR_DIRECTORS";

// Reviews
export const REQUEST_REVIEWS = "REQUEST_REVIEWS";
export const RECEIVE_REVIEWS = "RECEIVE_REVIEWS";
export const ERROR_REVIEWS = "ERROR_REVIEWS";
export const REQUEST_REVIEW_COUNTS = "REQUEST_REVIEW_COUNTS";
export const RECEIVE_REVIEW_COUNTS = "RECEIVE_REVIEW_COUNTS";
export const ERROR_REVIEW_COUNTS = "ERROR_REVIEW_COUNTS";
