export const EMPTY_MOVIE_DIRECTOR = "EMPTY_MOVIE_DIRECTOR";
export const EMPTY_MOVIE_TITLE = "EMPTY_MOVIE_TITLE";

export const INVALID_MOVIE_DATA_FORMAT = "INVALID_MOVIE_DATA_FORMAT";
export const INVALID_MOVIE_RATING = "INVALID_MOVIE_RATING";
export const INVALID_MOVIE_YEAR = "INVALID_MOVIE_YEAR";

export const MOVIE_RATING_TOO_HIGH = "MOVIE_RATING_TOO_HIGH";
export const MOVIE_RATING_TOO_LOW = "MOVIE_RATING_TOO_LOW";

export const MOVIE_YEAR_TOO_HIGH = "MOVIE_YEAR_TOO_HIGH";
export const MOVIE_YEAR_TOO_LOW = "MOVIE_YEAR_TOO_LOW";
